name: Process Boot Image with Payload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/apt
          ~/.ccache
          build
        key: ${{ runner.os }}-magiskboot-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Setup ccache
      run: |
        sudo apt install ccache -y
        echo "export PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV

    - name: Clone submodules
      run: |
        git submodule update --init --recursive
          
    - name: Install minimal dependencies
      run: |
        sudo apt update && sudo apt install -y \
          build-essential lzma-dev liblzma-dev liblz4-dev libbz2-dev \
          zlib1g-dev pkg-config clang-15 libc++-15-dev libc++abi-15-dev cmake \
          ninja-build rustc cargo
          
    - name: Build  MagiskBoot
      run: |
        git clone "https://github.com/PinNaCode/magiskboot_build.git"
        cd ./magiskboot_build
        echo "./scripts/clone_submodules.sh...."
        ./scripts/clone_submodules.sh
        CC=clang CXX=clang++ cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j $(nproc)
        cmake --install build
        
    - name: Process files
      run: |
        chmod +x ./process.sh
        ./process.sh
      env:
        BOOT_PATH: uploads/boot.img  # 用户上传文件的路径
        KERNEL_PATH: uploads/Image

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: new-boot.img
        path: ./destBoot
